version: '3'
services:
  website:
    image: nginx:latest
    container_name: Personal-Website  # Container name
    volumes:
      - /home/luca/Desktop/Personal-Website/src:/usr/share/nginx/html  # - <my folder's path>:/usr/share/nginx/html
    ports:
      - 1000:80  # - <server port (outside) [ex:1000]>:<container port (inside) [ex:80]>
    restart: unless-stopped  # Keeps the webside always running unless it gets manually stopped

# To update the website:
# 1) cd Desktop/Personal-Website
# 2) docker-compose down
# 3) cd /home/luca/Desktop
# 4) sudo rm -r Personal-Website
# 5) git clone https://github.com/MrPanda376/Personal-Website
# 6) cd Personal-Website
# 7) docker-compose up -d
