version: '3'
services:
  website:
    image: nginx:latest
    container_name: Personal-Website  # Nome container
    volumes:
      - /home/luca/Desktop/Personal-Website/src:/usr/share/nginx/html  # - <il path per la mia cartella>:/usr/share/nginx/html
    ports:
      - 1000:80  # Esponi la porta 80 del container sulla 1000 del server
    restart: unless-stopped  # Garantisce il riavvio automatico in caso di crash o riavvio del sistema
